preferences: {}
clusters:
  - name: 65f31611-88cf-4a55-bd9c-85e20a533c85
    cluster:
      server: https://10.0.0.206:6443
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkakNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTnpBNE5qWXlOVE13SGhjTk1qWXdNakV5TURNeE56TXpXaGNOTXpZd01qRXdNRE14TnpNegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTnpBNE5qWXlOVE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFRWVI1eWhqaEVNajNrenFiazZPRTRzTWViaG1aS2ovenFpNml3bEV1YmkKNXFjdHZRejZDL2JWTzlSTi9mNDQ0MkI1bHNYMzB0ZkorbHdBUmlBR1JGUGtvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUs4aUxWbjlUZzh3VUlPeER4WmxrCnE1MnlBc1F3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnYmtCc3BCZWlCaEsxdUg1Rk9EdnhNRlIwQU14TEhubHMKVytTODJESHdxaXdDSUdGbTFGaTNCZTE3Q0dLK3hyUTdyWk5ZbVBuSVZSbmh4V3ZzSStOM2g4cG4KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
users:
  - name: 65f31611-88cf-4a55-bd9c-85e20a533c85
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsImtpZCI6InV0aHlrR3A1TF80WEZUdFRSV1VHMThBVVQwdEZETlVxMGFFOEtCaGlITm8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWM2NTEwYTEtY2IyMi00ZDgyLWFmNzAtZWUxNjI1YTI2YTVkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YWRtaW4ifQ.AVHacLxGqRrfRYYIKsu0Qom5tdWNNQwiveHfFY_iiqm4goCnymaasNFT5TMM3k8UoPjJMztlRlQMMlSh4PKUvWdzyWcoLmVRil-k6hM4LklQGH1ZsbXk60NlFVZ6Qwa_L0-yEOvxWTjkn0r-l1ylp4v0pk3VA2jpLCuXth4Jh8YXrh99hFLzoZSMo0jbZ0s32ytKdJybwSSppR4K_y9B_m8dFSnK9vtVOiDwQt4iQlXKNlA1nZILq0eDQbzLT5hdLrCGCNzVflG0I804YTuUinxwHPO9dJVRCX1Q2BJd2GQEocUNl1Tt0UEVNVdDUB6pqskZNOd8ahB_8Geyf-UYWQ
contexts:
  - name: 65f31611-88cf-4a55-bd9c-85e20a533c85
    context:
      cluster: 65f31611-88cf-4a55-bd9c-85e20a533c85
      user: 65f31611-88cf-4a55-bd9c-85e20a533c85
current-context: 65f31611-88cf-4a55-bd9c-85e20a533c85
