{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "gpustack.fullname" . }}-worker
  annotations:
    w7.cc/title: "worker"
    title: "worker"
  labels:
    {{- include "gpustack.labels" . | nindent 4 }}
    {{- include "gpustackWorker.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gpustackWorker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gpustackWorker.selectorLabels" . | nindent 8 }}
        {{- with .Values.workerpodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      runtimeClassName: {{ .Values.runtimeClassName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gpustack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RELEASE_NAME_SUFFIX
              value: {{ .Release.Name }}
            - name: BOOTSTRAP_PASSWORD
              value: {{ .Values.bootstrapPassword }}  
            - name: SERVER_URL
              value: "http://{{ include "gpustack.fullname" . }}.{{ .Release.Namespace }}.svc"
            - name: TOKEN
              value: {{ .Release.Name }}  
          command:
            - /bin/sh
          args:
            - '-c'
            - 'gpustack start --server-url $SERVER_URL --token $TOKEN'
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            limits:
              memory: 0
              cpu: 0
              nvidia.com/gpu: {{ .Values.gpulimit.gpu | quote }}
              nvidia.com/gpucores: {{ .Values.gpulimit.gpucores | quote }}
              nvidia.com/gpumem: {{ .Values.gpulimit.gpumem | quote }}
            requests:
              nvidia.com/gpu: {{ .Values.gpulimit.gpu | quote }}
              nvidia.com/gpucores: {{ .Values.gpulimit.gpucores | quote }}
              nvidia.com/gpumem: {{ .Values.gpulimit.gpumem | quote }}
          {{- with .Values.volumeMountsWorker }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: gpustack
          persistentVolumeClaim:
            claimName: {{ include "gpustack.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}