apiVersion: v2
name: w7panel-offline
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
icon: https://zpk.w7.cc/zip/icon/w7panel_offline
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "1.0.123"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.123"

annotations:
  w7.cc/title: "微擎面板"
  w7.cc/description: "微擎面板"
  title: "微擎面板"
  w7.cc/icon: "https://zpk.w7.cc/zip/icon/w7panel_offline"
  w7.cc/zpk-url: "https://zpk.w7.cc/respo/info/w7panel_offline"
  w7.cc/identifie: "w7panel-offline"
